# DO NOT EDIT THIS FILE!
#
# Python module HangmanGame generated by omniidl

import omniORB
omniORB.updateModule("HangmanGame")

# ** 1. Stub files contributing to this module
import Hangman_idl

# ** 2. Sub-modules

# ** 3. End
